EXPAND_ARG = 'expand'
VALID_ARGS = ['id', 'limit', 'offset']

MANAGER_EXPANDED_RELATIONSHIP = 'manager'
OFFICE_EXPANDED_RELATIONSHIP = 'office'
DEPARTMENT_EXPANDED_RELATIONSHIP = 'department'
SUPER_DEPARTMENT_EXPANDED_RELATIONSHIP = 'superdepartment'
VALID_EXPANDED_RELATIONSHIPS = [
    MANAGER_EXPANDED_RELATIONSHIP,
    OFFICE_EXPANDED_RELATIONSHIP,
    DEPARTMENT_EXPANDED_RELATIONSHIP,
    SUPER_DEPARTMENT_EXPANDED_RELATIONSHIP
]

DEFAULT_ERR_MSG = [{'error': ''}]
DEFAULT_EMPTY_RES = []
